# Generated by Django 3.1.6 on 2021-02-26 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WearWareRESTAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylevel',
            name='participant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='WearWareRESTAPI.participant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='heartrate',
            name='participant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='WearWareRESTAPI.participant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participantstudy',
            name='enrollment_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='participantstudy',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='WearWareRESTAPI.participant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participantstudy',
            name='study',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='WearWareRESTAPI.study'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='researcherstudy',
            name='researcher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='WearWareRESTAPI.researcher'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='researcherstudy',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='WearWareRESTAPI.study'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sleepdata',
            name='participant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='WearWareRESTAPI.participant'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='activitylevel',
            unique_together={('participant', 'datetime')},
        ),
        migrations.AlterUniqueTogether(
            name='heartrate',
            unique_together={('participant', 'datetime')},
        ),
        migrations.AlterUniqueTogether(
            name='participantstudy',
            unique_together={('study', 'participant')},
        ),
        migrations.AlterUniqueTogether(
            name='researcherstudy',
            unique_together={('researcher', 'study')},
        ),
        migrations.AlterUniqueTogether(
            name='sleepdata',
            unique_together={('participant', 'datetime')},
        ),
        migrations.RemoveField(
            model_name='activitylevel',
            name='participant_id',
        ),
        migrations.RemoveField(
            model_name='heartrate',
            name='participant_id',
        ),
        migrations.RemoveField(
            model_name='participantstudy',
            name='participant_id',
        ),
        migrations.RemoveField(
            model_name='participantstudy',
            name='partipant_id_pk',
        ),
        migrations.RemoveField(
            model_name='participantstudy',
            name='study_id',
        ),
        migrations.RemoveField(
            model_name='researcherstudy',
            name='researcher_id',
        ),
        migrations.RemoveField(
            model_name='researcherstudy',
            name='study_id',
        ),
        migrations.RemoveField(
            model_name='sleepdata',
            name='participant_id',
        ),
    ]
