# Generated by Django 3.1.7 on 2021-03-08 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WearWareRESTAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitbitheartrecord',
            name='minute_record',
        ),
        migrations.AddField(
            model_name='fitbitheartrecord',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WearWareRESTAPI.fitbitaccount'),
            preserve_default=False,
        ),
    ]
