# Generated by Django 3.1.7 on 2021-03-08 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WearWareRESTAPI', '0002_auto_20210308_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitbitheartrecord',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WearWareRESTAPI.fitbitminuterecord'),
        ),
    ]
