# Generated by Django 3.1.3 on 2021-03-14 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WearWareRESTAPI', '0003_auto_20210308_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_level', models.ManyToManyField(related_name='_participantdata_activity_level_+', to='WearWareRESTAPI.FitbitMinuteRecord')),
                ('bpm', models.ManyToManyField(related_name='_participantdata_bpm_+', to='WearWareRESTAPI.FitbitHeartRecord')),
                ('calories', models.ManyToManyField(related_name='_participantdata_calories_+', to='WearWareRESTAPI.FitbitMinuteRecord')),
                ('device', models.ManyToManyField(related_name='_participantdata_device_+', to='WearWareRESTAPI.FitbitHeartRecord')),
                ('distance', models.ManyToManyField(related_name='_participantdata_distance_+', to='WearWareRESTAPI.FitbitMinuteRecord')),
                ('mets', models.ManyToManyField(related_name='_participantdata_mets_+', to='WearWareRESTAPI.FitbitMinuteRecord')),
                ('steps', models.ManyToManyField(related_name='_participantdata_steps_+', to='WearWareRESTAPI.FitbitMinuteRecord')),
            ],
        ),
    ]
